import LocalizedStrings from "react-native-localization"

const StringsOfLanguages = new LocalizedStrings({
    en: {
        HELP:"HELP",
        login_signup : "Login or SignUp",
        remember_me:"Remember me",
        email_phone:"Email or phone",
        password:"Password",
        current_appointments:"Current Appointments",
        sign_in:"SIGN ME IN",
        forgot_password:"Forgot your password? Tap to get it!",
        no_account:"Don't have an account?",
        agree_to_terms_alert:"You must agree to terms and conditions",
        upload_success:"Upload Successful",
        select_file_first:"Please Select File first",
        register:"Register",
        full_name:"Full Name",
        phone_number:"Phone Number",
        email:"Email",
        address:"Address",
        file_name:"File Name",
        type:"Type",
        file_size:"File size",
        uri:"URI",
        ID_police_cert:"IDENTIFIANT. / Rapport de police / Certification",
        select_files:"Select Files",
        upload_files:"Upload Files",
        ID_police_cert_uploaded:"I.D. / Police Report / Certification Uploaded",
        agree_to_terms:"I agree to terms and conditions",
        create_account:"CREATE AN ACCOUNT",
        login:"Login",
        homepage_title:"Looking for a professional handyman?",
        homepage_sentence_one:"Quality handyman service you can trust.",
        homepage_sentence_two:"Moving, cleaning, mounting, gardening and more",
        get_started:"Get Started",
        select_dob:"Select DOB file",
        upload:'upload',
        home:"Home",
        welcome:"Welcome",
        schedule:"Schedule",
        slot:"Slot",
        timer:"Timer",
        more_time:"More Time",
        message:"Message",
        job_request:"Job Request",
        dashboard:"Dashboard",
        all_messages:"All Messages",
        earnings:"Earnings",
        my_jobs:"My Jobs",
        help:"Help",
        my_account:"My Account",
        todays_jobs:"Today's Jobs",
        sameday_jobs:"Sameday Jobs",
        jobs:"Jobs",
        commissions_owed:"Commissions Owed",
        customers:"Customers",
        latest_messages:"Latest Messages",
        accept:"Accept",
        reject:"Reject",
        view_more:"View More",
        emergency:"Emergency",
        today:"Tody",
        sameday:"Sameday",
        scheduled:"Scheduled",
        enter_text:"Enter Text",
        edit:"Edit",
        log_out:"Log Out",
        save:"Save",
        certified:"Certified",
        choose_language:"Choose A Language",
        choose_one:"Choose One",
        code:"Enter code",
    },
    fr: {
        HELP:"HELP",
        login_signup : "Identifiez-vous ou inscrivez-vous",
        remember_me:"Souviens-toi de moi",
        email_phone:"Email ou téléphone",
        password:"Mot de passe",
        current_appointments:"Nominations en cours",
        sign_in:"INSCRIVEZ-MOI",
        forgot_password:"Mot de passe oublié? Appuyez pour l'obtenir !",
        no_account:"Vous n'avez pas de compte ?",
        agree_to_terms_alert:"Vous devez accepter les termes et conditions",
        upload_success:"Téléchargement réussi",
        select_file_first:"Veuillez d'abord sélectionner le fichier",
        register:"S'inscrire",
        full_name:"Nom et prénom",
        phone_number:"Numéro de téléphone",
        email:"E-mail",
        address:"Adresse",
        file_name:"Nom de fichier",
        type:"Taper",
        file_size:"Taille du fichier",
        uri:"URI",
        ID_police_cert:"IDENTIFIANT. / Rapport de police / Certification",
        select_files:"Sélectionnez les fichiers",
        upload_files:"Télécharger des fichiers",
        ID_police_cert_uploaded:"IDENTIFIANT. / Rapport de police / Certification téléchargée",
        agree_to_terms:"J'accepte les termes et conditions",
        create_account:"CRÉER UN COMPTE",
        login:"Connexion",
        homepage_title:"Vous cherchez un bricoleur professionnel ?",
        homepage_sentence_one:"Un service de bricolage de qualité en qui vous pouvez avoir confiance.",
        homepage_sentence_two:"Déménagement, nettoyage, montage, jardinage et plus",
        get_started:"Commencer",
        select_dob:"Sélectionner DOB dossier",
        upload:'télécharger',
        home:"Maison",
        welcome:"Bienvenue",
        schedule:"Programme",
        slot:"Insérer",
        timer:"Minuteur",
        more_time:"Plus de temps",
        message:"Message",
        job_request:"Demande d'emploi",
        dashboard:"Tableau de bord",
        all_messages:"Tous les messages",
        earnings:"Gains",
        my_jobs:"Mes travaux",
        help:"Aider",
        my_account:"Mon compte",
        todays_jobs:"Les métiers d'aujourd'hui",
        sameday_jobs:"Emplois le jour même",
        jobs:"Travaux",
        commissions_owed:"Commissions dues",
        customers:"Clients",
        latest_messages:"Derniers messages",
        accept:"Accepter",
        reject:"Rejeter",
        view_more:"Voir plus",
        emergency:"Urgence",
        today:"Aujourd'hui",
        sameday:"Même jour",
        scheduled:"Programmé",
        enter_text:"Entrez du texte",
        edit:"Éditer",
        log_out:"Se déconnecter",
        save:"Sauvegarder",
        certified:"Agréé",
        choose_language:"Choisissez une langue",
        choose_one:"Choisissez-en un",
        code:"Entrez le code",
    },
    ar:{
        HELP:"HELP",
        login_signup :"تسجيل الدخول أو الاشتراك",
        remember_me:"تذكرنى",
        email_phone:"بريد الكتروني او هاتف",
        password:"كلمة المرور",
        current_appointments:"المواعيد الحالية",
        sign_in:"سجل دخولي",
        forgot_password:"نسيت رقمك السري؟ انقر للحصول عليه!",
        no_account:"ليس لديك حساب؟",
        agree_to_terms_alert:"يجب أن توافق على الشروط والأحكام",
        upload_success:"تحميل ناجح",
        select_file_first:"الرجاء تحديد الملف أولاً",
        register:"يسجل",
        full_name:"الاسم الكامل",
        phone_number:"رقم الهاتف",
        email:"البريد الإلكتروني",
        address:"تبوك",
        file_name:"اسم الملف",
        type:"يكتب",
        file_size:"حجم الملف",
        uri:"URI",
        ID_police_cert:"بطاقة تعريف. / تقرير شرطة / تصديق",
        select_files:"اختر الملفات",
        upload_files:"تحميل الملفات",
        ID_police_cert_uploaded:"بطاقة تعريف. / تقرير الشرطة / تم تحميل الشهادة",
        agree_to_terms:"أوافق على البنود والشروط",
        create_account:"انشئ حساب",
        login:"تسجيل الدخول",
        homepage_title:"هل تبحث عن عامل بارع محترف؟",
        homepage_sentence_one:"جودة خدمة بارع يمكنك الوثوق بها.",
        homepage_sentence_two:"نقل وتنظيف وتركيب وبستنة والمزيد",
        get_started:"البدء",
        select_dob:"يختار DOB ملف",
        upload:'تحميل',
        home: "مسكن",
        welcome:"أهلا وسهلا",
        schedule:"برنامج",
        slot:"فتحة",
        timer:"الموقت",
        more_time:"المزيد من الوقت",
        message:"رسالة",
        job_request:"طلب وظيفة",
        dashboard:"لوحة القيادة",
        all_messages:"جميع الرسائل",
        earnings:"أرباح",
        my_jobs:"وظائفي",
        help:"مساعدة",
        my_account:"حسابي",
        todays_jobs:"وظائف اليوم",
        sameday_jobs:"Sameday وظائف",
        jobs:"وظائف",
        commissions_owed:"العمولات المستحقة",
        customers:"عملاء",
        latest_messages:"أحدث الرسائل",
        accept:"قبول",
        reject:"رفض",
        view_more:"عرض المزيد",
        emergency:"طارئ",
        today:"اليوم",
        sameday:"Sameday",
        scheduled:"المقرر",
        enter_text:"أدخل النص",
        edit:"يحرر",
        log_out:"تسجيل خروج",
        save:"يحفظ",
        certified:"معتمد",
        choose_language:"اختر لغة",
        choose_one:"اختر واحدة",
        code:"ادخل الرمز",
    },

});

export default StringsOfLanguages;